export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REAUEST_ROBOTS_PENDING = 'REAUEST_ROBOTS_PENDING';
export const REAUEST_ROBOTS_SUCCESS = 'REAUEST_ROBOTS_SUCCESS';
export const REAUEST_ROBOTS_FAILED = 'REAUEST_ROBOTS_FAILED';